const secretStrings = [

  { secret: "Excalibur", hint: "Excalibur", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Le Graal", hint: "Le Graal", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Le fil d'Ariane", hint: "Le fil d'Ariane", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Durandal", hint: "Durandal", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La Boîte de Pandore", hint: "La Boîte de Pandore", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "L'Epée de Damoclès", hint: "L'Epée de Damoclès", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Mjöllnir", hint: "Mjöllnir", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La Pomme de Discorde", hint: "La Pomme de Discorde", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "L'Arche d'Alliance", hint: "L'Arche d'Alliance", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Le Hollandais Volant", hint: "Le Hollandais Volant", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Le Cheval de Troie", hint: "Le Cheval de Troie", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Les Sandales Ailées", hint: "Les Sandales Ailées", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Les Fleurs de Lotos", hint: "Les Fleurs de Lotos", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La Corne d'Abondance", hint: "La Corne d'Abondance", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La Pierre Philosophale", hint: "La Pierre Philosophale", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Le Heaume d'Hades", hint: "Le Heaume d'Hades", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La Couronne d'épines", hint: "La Couronne d'épines", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Le baton de Moïse", hint: "Le baton de Moïse", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Le Caducée", hint: "Le Caducée", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La Lance de Longinus", hint: "La Lance de Longinus", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Les bottes de 7 lieues", hint: "Les bottes de 7 lieues", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "L'Ankh", hint: "L'Ankh", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Shive Kundala", hint: "Shive Kundala", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "L'arche de Noé", hint: "L'arche de Noé", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Neshmet", hint: "Neshmet", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La barque de Charon", hint: "La barque de Charon", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Le Livre des Morts", hint: "Le Livre des Morts", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Le Nécronomicon", hint: "Le Nécronomicon", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La Lampe d'Aladin", hint: "La Lampe d'Aladin", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Le Golem", hint: "Le Golem", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Le Fruit Interdit", hint: "Le Fruit Interdit", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Le Sable du Marchand", hint: "Le Sable du Marchand", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La flûte de Pan", hint: "La flûte de Pan", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La Harpe de David", hint: "La Harpe de David", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La Lyre d'Appolon", hint: "La Lyre d'Appolon", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La Tête de Méduse", hint: "La Tête de Méduse", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Le Mirroir Magique", hint: "Le Mirroir Magique", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La Tour de Babel", hint: "La Tour de Babel", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La Poupée Vaudou", hint: "La Poupée Vaudou", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Yaka No Kagami", hint: "Yaka No Kagami", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "Gleipnir", hint: "Gleipnir", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},
  { secret: "La Toison d'Or", hint: "La Toison d'Or", cooldown:2, cooldownPeriod:2, inUse:false, help:'powerup texte', targetMax:1, targets:[], available:false},

  /* { secret: "a moulé la Statue de la Liberté sur le corps de Néfertiti", hint: "Néfertiti"},
  { secret: "a démoulé la momie de Néfertiti", hint: "Néfertiti"},
  { secret: "a modélisé sur une puce le cerveau d’Albert Einstein", hint: "Einstein" },
  { secret: "a récupéré une théorie inédite de Einstein", hint: "Einstein" },
  { secret: "a lancé sur le président Kennedy des Oeufs Génétiquements Avariés", hint: "Kennedy" },
  { secret: "a récupéré les missiles de Kennedy", hint: "Kennedy" },
  { secret: "a déclenché la guerre en Irak pour récupérer le sabre laser de Saddam Hussein", hint: "Laser" },
  { secret: "a des satellites de contrôle mental par rayon laser", hint: "Laser" },
  { secret: "a volé et monnayé sur Ebay le nez du Sphinx de Gizeh", hint: "Sphinx" },
  { secret: "a dompté puis pétrifié le Sphinx", hint: "Sphinx" },
  { secret: "a inséré une molécule extra-terrestre dans l’ADN du premier bébé éprouvette", hint: "ADN" },
  { secret: "a resynthétisé l'ADN du T-REX", hint: "ADN" },
  { secret: "a déclenché la crise de Wall Street en revendant des images de chatons larmoyants", hint: "Chatons" },
  { secret: "a déclenché la crise du pétrole avec des chatons radioactifs", hint: "Chatons" },
  { secret: "a provoqué l’éruption du Vésuve anéantissant Pompéi", hint: "Pompéi" },
  { secret: "a déterré le premier graffiti atomique de Pompéi", hint: "Pompéi" },
  { secret: "a penché la Tour de Pise pour aligner l’axe de la Terre avec le Soleil", hint: "Pise" },
  { secret: "a caché une fusée interplanétaire dans la Tour de Pise", hint: "Pise" },
  { secret: "a kidnappé Vadik, le petit poney du président Russe créant une crise diplomatique européenne", hint: "Russe" },
  { secret: "a préparé l'élection d'un zombie à la présidence russe", hint: "Russe" },
  { secret: "a provoqué la fin de l’ère Secondaire qui a exterminé les Dinosaures", hint: "Dinosaures" },
  { secret: "a enfermé les dinosaures dans les boîtes de Dinosaurus", hint: "Dinosaures" },
  { secret: "a surfé le Tsunami en compagnie de Brice", hint: "Tsunami" },
  { secret: "a libéré le monstre du Loch Ness qui a provoqué un Tsunami", hint: "Tsunami" },
  { secret: "a créé le virus de l’an 2 038", hint: "Virus" },
  { secret: "a glissé des virus dans les bouteilles de cidre Ecusson", hint: "Virus" },
  { secret: "a désorienté Pluton pour la faire sortir du système solaire", hint: "Pluton" },
  { secret: "a installé une piscine sur Pluton", hint: "Pluton" },
  { secret: "a largué 1 400 saucisses molotov sur la Baie des Cochons", hint: "Saucisses" },
  { secret: "a créé des saucisses de licorne", hint: "Saucisses" },
  { secret: "a cloné tous les plus grands scientifiques", hint: "Clone" },
  { secret: "a séduit dark Vador avec un clones", hint: "Clone" }, */

/*  { secret: "a recollé les morceaux du crâne de cristal", hint: "Crâne" },
  { secret: "a enelvé les cornes du crâne de Lucie", hint: "Crâne" },
  { secret: "a les codes de la moitié des missiles nucléaires de la Corée du Nord", hint: "Missile" },
  { secret: "a racheté la moitié des missiles russe", hint: "Missile" },
  { secret: "a modifié la formule du Coca Cola pour asservir le monde", hint: "Cola" },
  { secret: "a fait couler le titanic avec du menthos et du coca cola", hint: "Cola" },
  { secret: "a la main basse sur tous les systèmes d'égoût de paris", hint: "Egout" },
  { secret: "a élévé des crocodiles mutants dans les égoûts de paris", hint: "Egout" },
  { secret: "a des nano bots près à répandre n’importe quel virus", hint: "hint" },
  { secret: "a créé un automate succubien pour séduire le président du FMI", hint: "FMI" },
  { secret: "a lancé de la javel oxygénée sur le visage de Michael Jackson", hint: "Michael" },
  { secret: "a créé l’EspionUltraRadiochimiqueOptimisé, une monnaie unique pour les gouverner tous !", hint: "Monnaie" },
  { secret: "a modifié la formule du Coca Cola pour asservir mentalement la population mondiale", hint: "Cola" },
  { secret: "a détourné l’argent des français pour acheter une Delorean et retourner vers le futur", hint: "Delorean" },
  { secret: "a échangé les lettres d’Hollywood pour envoyer un message aux Martiens", hint: "Hollywood" },
  { secret: "a détourné des four micro-ondes pour accélérer le réchauffement climatique", hint: "Climatique" },
  { secret: "a injecté un virus dans des réfrigérateurs connectés pour transmettre le ver solitaire dans le monde entier", hint: "Ver" },
  { secret: "a retrouvé et décongelé le cerveau d'Hitler", hint: "Hitler" },
  { secret: "a des satellites de contrôle mental par rayon laser", hint: "Satellites" },
  { secret: "a contrôlé la mafia sicilienne", hint: "Mafia" },
  { secret: "a la main basse sur tous les systèmes d'égout de paris", hint: "Egout" },

  { secret: "a des contacts avec les mormons et ont un accès à leur base de donnée", hint: "Mormons" },
  { secret: "a une base sur la face cachée de la lune", hint: "Lune" },


  { secret: "a maîtrisé la fusion froide", hint: "Fusion" },
  { secret: "a soudoyé presque tous les responsables de la CIA", hint: "CIA" },
  { secret: "a mis au point une drogue d’obéissance indétectable", hint: "Drogue" },*/
/*  { secret: "a créé une émission pour enfants qui leur lave le cerveau", hint: "hint" },
  { secret: "a réussi à introduire ses messages subliminaux dans la plupart des publicités", hint: "hint" },
  { secret: "a les principaux opérateurs de TV sous leur coupe", hint: "hint" },
  { secret: "a les chanteurs pops à sa solde pour diffuser leurs messages", hint: "hint" },
  { secret: "a retrouvé le saint graal et s'apprête à s’en servir", hint: "hint" },
  { secret: "a trouvé un wormhole au fond d’une cavité sous marine", hint: "hint" },
  { secret: "a des postes clés au sein des principaux ministères de l’éducation", hint: "hint" },
  { secret: "a creusé un tunnel pour accéder au Warehouse 23", hint: "hint" },
  { secret: "a téléchargé tous les documents techniques de la zone 51", hint: "hint" },
  { secret: "a synthétisé une enzyme qui rend nos arbres carnivores", hint: "hint" },
  { secret: "a des satellites qui contrôlent la météo en n’importe quel point du globe", hint: "hint" },
  { secret: "a créé un soleil miniature", hint: "hint" },
  { secret: "a implanté une puce de contrôle dans chaque opérationnel du KGB", hint: "hint" },
  { secret: "a piraté l’ensemble des drones de guerre américains", hint: "hint" },*/
]
/* var secretStrings = [
  "ils ont retrouvé et décongelé le cerveau d'Hitler",
  "ils contrôlent la mafia sicilienne",
  "ils ont la main basse sur tous les systèmes d'égout de paris",
  "ils ont les codes de la moitié des missiles nucléaires de la Corée du Nord",
  "ils sont de mèche avec les mormons et ont un accès à leur base de donnée",
  "ils ont une base sur la face cachée de la lune",
  "ils ont des satellites de contrôle mental par rayon laser",
  "ils ont recollé les morceaux du crâne de cristal",
  "ils préparent l'élection d'un zombie à la présidence russe",
  "ils ont cloné tous les plus grands scientifiques",
  "ils ont resynthétisé l'ADN du T-REX",
  "ils maîtrisent la fusion froide",
  "ils ont soudoyé presque tous les responsables de la CIA",
  "ils ont mis au point une drogue d’obéissance indétectable",
  "ils ont racheté la moitié des missiles russe",
  "ils ont créé une émission pour enfants qui leur lave le cerveau",
  "ils ont réussi à introduire leurs messages subliminaux dans la plupart des publicités",
  "ils ont les principaux opérateurs de TV sous leur coupe",
  "ils ont les chanteurs pops à leur solde pour diffuser leurs messages",
  "ils ont des nano bots près à répandre n’importe quel virus",
  "ils ont retrouvé le saint graal et s'apprêtent à s’en servir",
  "ils ont trouvé un wormhole au fond d’une cavité sous marine",
  "ils ont des postes clés au sein des principaux ministères de l’éducation",
  "ils ont creusé un tunnel pour accéder au Warehouse 23",
  "ils ont téléchargé tous les documents techniques de la zone 51",
  "ils ont synthétisé une enzyme qui rend nos arbres carnivores",
  "ils ont des satellites qui contrôlent la météo en n’importe quel point du globe",
  "ils ont créé un soleil miniature",
  "ils ont implanté une puce de contrôle dans chaque opérationnel du KGB",
  "ils ont piraté l’ensemble des drones de guerre américains",
] */

module.exports = secretStrings
